### ISSUE TITLE
Aufgabenblatt 1

### ISSUE THREAD

**Issue by paulesn** [FIUS/jvk#22]
Lernziele:

_Praktische Lernziele:_

 *  Projekt Importieren und Starten können
 *  Code Copy&Paste der Compiled
 *  Syntax erkennen und Begriffen zuordnen können
     *  Klasse { Methode {code}} (schachtelung!)
     *  `Typ var = Objekt;`
     *  `new Typ(42)`
     *  `var.doSomething()`
     *  `x = var.getSomething()`
     *  Semikolon und Einrückung
     *  Klammerung für () und {}
     *  `"string"` und `42` zahl
 *  Programmfluss ganz grob verstehen (nur in der main Methode der main klasse)
 *  Javadoc einer Methode finden
 *  Javadoc einer Klasse finden
 *  Methoden einer Klasse/eines Objekts finden
 *  Bewusst fehler im Programm erzeugen können und ihre Auswirkung beobachten können
 *  Nach einem Fehler wieder zu einem funktionierenden (z.B. früheren) programmzustand zurückkehren können
 *  Spielfeld verstehen (Koordiaten)

_Theoretische Lernziele:_

 *  Objekte und Klassen grob verstanden haben (in minimalem uml syntax)
 *  Ein paar Objekte/Klassen aus einem Text heraus abstrahieren? (ohne advanced uml sachen wie vererbung oder verbindungen zwischen klassen)

**Aufgaben**

- [x]  [Aufgabe 1](https://github.com/FIUS/jvk/issues/23)
- [x]  [Aufgabe 2](https://github.com/FIUS/jvk/issues/24)
- [x]  [Aufgabe 3](https://github.com/FIUS/jvk/issues/25)
- [x]  [Aufgabe 4](https://github.com/FIUS/jvk/issues/26)
- [x]  [Aufgabe 5](https://github.com/FIUS/jvk/issues/27)
