### ISSUE TITLE
Arbeitsblatt 2

### ISSUE THREAD

**Issue by paulesn** [FIUS/jvk#28]
Lernziele:

 *  Player spawnen und bewegen können
 *  Collectables aufheben können und ablegen können
 *  Exceptions in der Konsole erkennen können
 *  Die Zeile der Exception im code wiederfinden können (in einem speziell dafür gemachten Beispiel für eine Aufgabe)
 *  Eine Beispiel Exception auflösen können (egal wie, selbst mit auskommentieren)
 *  Conditional move() (if (canMove) {doMove} else {turn})
 *  While(canMove) {doMove} schleife abschreiben und korrekt anwenden können
 *  While(canPickup) {doPickup} schleife abschreiben und korrekt anwenden können
 *  Erste eigene Operation turnLeft (hier oder im nächsten Blatt erst)

**Aufgaben**

- [x] [Aufgabe 1](https://github.com/FIUS/jvk/issues/29)
- [x] [Aufgabe 2](https://github.com/FIUS/jvk/issues/30)
- [x] [Aufgabe 3](https://github.com/FIUS/jvk/issues/31)
- [x] [Aufgabe 4](https://github.com/FIUS/jvk/issues/32)
- [x] [Aufgabe 5](https://github.com/FIUS/jvk/issues/33)
- [x] [Aufgabe 6](https://github.com/FIUS/jvk/issues/34)
