### ISSUE TITLE
Blatt 3 

### ISSUE THREAD

**Issue by paulesn** [FIUS/jvk#40]
Lernziele

    For schleife um etwas exakt n mal auszuführen (abschreiben und zahl ersetzen)
    Allgemeineres If-Then-Else
    Allgemeineres While
    Einfache Operationen (in den tasks und in entities) selber schreiben
    Einfache parameter in operationen verwenden können
    Return um aus einer methode zu springen (ohne rückgabewert)
    Verhalten in Methoden auf der Entity auslagern und in mehreren Tasks verwenden können

Für Alle Methoden im gesamten Blatt sollte Dokumentation in form von Javadoc eingefordert werden.

- [ ] [Aufgabe 1](https://github.com/FIUS/jvk/issues/38)
- [ ] [Aufgabe 2](https://github.com/FIUS/jvk/issues/39)
- [ ] [Aufgabe 3](https://github.com/FIUS/jvk/issues/40)
- [ ] [Aufgabe 4](https://github.com/FIUS/jvk/issues/41)
- [ ] [Aufgabe 5](https://github.com/FIUS/jvk/issues/42)
- [ ] [Aufgabe 6](https://github.com/FIUS/jvk/issues/43)
