### ISSUE TITLE
Blatt 4 

### ISSUE THREAD

**Issue by paulesn** [FIUS/jvk#46]
Komplexe Spielfelder selber bauen können mit shapes und dem playfield builder
    (Private) Attribute einer Klasse als Objekteigene Variablen verstehen
    Eigene Shape Objekte implementieren können (z.B. Smiley, some form of Triangle, filled rectangles)
    Eigene Programm-Objekte erstellen können
    Verhalten in Programme auslagern und in mehreren Tasks verwenden können

- [ ] [Aufgabe 1](https://github.com/FIUS/jvk/issues/45)
- [ ] [Aufgabe 2](https://github.com/FIUS/jvk/issues/46)
- [ ] [Aufgabe 3](https://github.com/FIUS/jvk/issues/47)
